# Generated by Django 5.1 on 2026-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='email_dpo',
            field=models.EmailField(max_length=254, verbose_name='E-mail do DPO'),
        ),
    ]
